package math.writer;

import math.geometry.model.Edge;
import math.geometry.model.InLayerJoint;
import math.geometry.model.InterLayerJoint;
import math.geometry.model.Vertex;

public class WriterVisitorAbaqus implements WriterVisitor {

    public String generateHeader() {

	String head = "*Heading" + "\n" + "** Job name: Analisys Model name: FDM_Model" + "\n"
		+ "** Generated by: Abaqus Builder" + "\n" + "*Preprint, echo=NO, model=NO, history=NO, contact=NO"
		+ "\n" + "**" + "\n" + "** PARTS" + "\n" + "**" + "\n" + "*Part, name=FDM_Print" + "\n" + "*End Part"
		+ "\n" + "**" + "\n" + "**" + "\n" + "** ASSEMBLY" + "\n" + "**" + "\n" + "*Assembly, name=Assembly"
		+ "\n" + "**" + "\n" + "*Instance, name=FDM_Print-1, part=FDM_Print" + "\n" + "*Node";

	return head;
    }

    @Override
    public String generateNodes(Vertex vertex) {
	String vertices = "";
	double x = vertex.getX();
	double y = vertex.getY();
	double z = vertex.getZ();
	int id = vertex.getId();
	return vertices + id + ", " + x + ", " + y + ", " + z;
    }

    public String generateMiddle() {
	return "";
    }

    @Override
    public String generateElements(Edge edge) {
	int edgeId = edge.getEdgeId();
	int v1Id = edge.getVertex1().getId();
	int v2Id = edge.getVertex2().getId();
	return edgeId + ", " + v1Id + ", " + v2Id;
    }

    @Override
    public String generateInPlaneJoint(InLayerJoint inPlaneJoint) {
	int edgeId = inPlaneJoint.getEdgeId();
	int v1Id = inPlaneJoint.getVertex1().getId();
	int v2Id = inPlaneJoint.getVertex2().getId();
	return edgeId + ", " + v1Id + ", " + v2Id;
    }

    @Override
    public String generateInterLayerJoint(InterLayerJoint interLayerJoint) {
	int edgeId = interLayerJoint.getEdgeId();
	int v1Id = interLayerJoint.getVertex1().getId();
	int v2Id = interLayerJoint.getVertex2().getId();
	return edgeId + ", " + v1Id + ", " + v2Id;
    }

    public String generateBottom() {

	String bottom = "** Section: edge  Profile: Circle" + "\n"
		+ "*Beam Section, elset=edge, material=ABS, temperature=GRADIENTS, section=CIRC" + "\n"
		//
		+ "0.25" + "\n"
		//
		+ "0.,0.,-1" + "\n"
		//
		+ "**" + "\n"
		//
		+ "** Section: inLayerJoint  Profile: Circle" + "\n"
		//
		+ "*Beam Section, elset=inLayerJoint, material=ABS, temperature=GRADIENTS, section=CIRC" + "\n"
		//
		+ "0.1" + "\n"
		//
		+ "0.,0.,-1" + "\n"
		//
		+ "** Section: interLayerJoint  Profile: Circle" + "\n"
		//
		+ "*Beam Section, elset=interLayerJoint, material=ABS, temperature=GRADIENTS, section=CIRC" + "\n"
		//
		+ "0.1" + "\n"
		//
		+ "0.,0.,-1" + "\n"
		//
		+ "*End Instance" + "\n"
		//
		+ "**" + "\n"
		//
		+ "*End Assembly" + "\n"
		//
		+ "** MATERIALS" + "\n"
		//
		+ "**" + "\n"
		//
		+ "*Material, name=ABS" + "\n"
		//
		+ "*Elastic" + "\n"
		//
		+ "1.4e+06, 0.35";
	return bottom;
    }

}
