package math.writer;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;

import math.abaqus.AbaqusModel;
import math.abaqus.AbaqusModelBuilder;

public class Writer {

    public void write(AbaqusModel model, AbaqusModelBuilder builder) {

	PrintWriter printWriter = null;
	try {
	    printWriter = new PrintWriter("FDM_Model.inp", "UTF-8");
	} catch (FileNotFoundException e) {
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	} catch (UnsupportedEncodingException e) {
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}
	printWriter.println("** Job name: Analisys Model name: FDM_Model");
	printWriter.println("** Generated by: Abaqus Builder");
	printWriter.println("*Preprint, echo=NO, model=NO, history=NO, contact=NO");
	printWriter.println("**");
	printWriter.println("** PARTS");
	printWriter.println("**");
	printWriter.println("*Part, name=FDM_Print");
	printWriter.println("*End Part");
	printWriter.println("**");
	printWriter.println("**");
	printWriter.println("** ASSEMBLY");
	printWriter.println("**");
	printWriter.println("*Assembly, name=Assembly");
	printWriter.println("** ");
	printWriter.println("*Instance, name=FDM_Print-1, part=FDM_Print");
	printWriter.println("*Node");
	printWriter.println(model);
	printWriter.println("*End Instance");
	printWriter.println("**");
	printWriter.println("*End Assembly");

	printWriter.close();
    }

}
